#!/bin/sh
# set -e

# cleanup() {
#     exec 3>&-
# 	rm "$FIFO_UEBERZUG"
# }

# if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
# 	lf "$@"
# else
# 	[ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
# 	export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
# 	mkfifo "$FIFO_UEBERZUG"
# 	ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
# 	exec 3>"$FIFO_UEBERZUG"
# 	trap cleanup EXIT
# 	lf "$@" 3>&-
# fi
set -e

if [ -n "$DISPLAY" ]; then
  export FIFO_UEBERZUG="${TMPDIR:-/tmp}/lf-ueberzug-$$"

  cleanup() {
    exec 3>&-
    rm "$FIFO_UEBERZUG"
  }

  mkfifo "$FIFO_UEBERZUG"
  ueberzug layer -s <"$FIFO_UEBERZUG" &
  exec 3>"$FIFO_UEBERZUG"
  trap cleanup EXIT

  if ! [ -d "$HOME/.cache/lf" ]; then
    mkdir -p "$HOME/.cache/lf"
  fi

  lf "$@" 3>&-
else
  exec lf "$@"
fi
