[keybindings]
"-" = "voldown 10"
"=" = "volup 10"
"z" = "previous" 
"b" = "next"
"gg" = "move top"
"Shift+g" = "move bottom"
"4" = "focus queue"
"Shif+f" = "focus search"
"2" = "focus library"
"<" = "seek -60000"
">" = "seek +60000"
"," = "seek -5000"
"." = "seek +5000"
"Shift+e" = "queue; move down 1"
"c" = "playpause"
"r" = "repeat"
"Shift+s" = "save"
"s" = "shuffle"
"e" = "playnext; move down 1"

[theme]
background = "black"
primary = "#F8F8F2"
secondary = "light black"
title = "#bd93f9"
playing = "#bd93f9"
playing_selected = "#D0B3FA"
playing_bg = "black"
highlight = "#f1fa8c"
highlight_bg = "#44475a"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "black"
statusbar_progress = "#bd93f9"
statusbar_bg = "#bd93f9"
cmdline = "#f8f8f2"
cmdline_bg = "black"
search_match = "#ff79c6"
